name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies using yarn
      - name: Install dependencies
        run: yarn install

      # Step 4: Run the linter
      - name: Lint the project
        run: yarn lint

      # Step 5: Start the application
      - name: Start the application
        run: yarn start & # Start the server in the background
        env:
          NODE_ENV: test # Set the environment to test

      # Step 6: Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to be ready..."
          timeout 30s bash -c "until curl -s http://localhost:3000/animals; do sleep 1; done"

      # Step 7: Run tests
      - name: Run tests
        run: yarn test

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 9: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # The Dockerfile is in the root of the repository
          tags: samdw/webapp:latest
          push: true # Push the image to Docker Hub
